library(dplyr)
library(stringr)

GeoLabels <- tribble(
    ~Geolocation, ~Region, ~Reg_Num, ~Province,
    "PHILIPPINES", "Philippines", "Philippines", "Philippines",
    "..NATIONAL CAPITAL REGION (NCR)", "NCR", "NCR", "NCR",
    "..CORDILLERA ADMINISTRATIVE REGION (CAR)", "CAR", "CAR", "CAR",
    "....Abra", "CAR", "CAR", "Abra",
    "....Apayao", "CAR", "CAR", "Apayao",
    "....Benguet", "CAR", "CAR", "Benguet",
    "....Ifugao", "CAR", "CAR", "Ifugao",
    "....Kalinga", "CAR", "CAR", "Kalinga",
    "....Mountain Province", "CAR", "CAR", "Mountain Province",
    "..REGION I (ILOCOS REGION)", "Ilocos Region", "Reg. I", "Reg. I",
    "....Ilocos Norte", "Ilocos Region", "Reg. I", "Ilocos Norte",
    "....Ilocos Sur", "Ilocos Region", "Reg. I", "Ilocos Sur",
    "....La Union", "Ilocos Region", "Reg. I", "La Union",
    "....Pangasinan", "Ilocos Region", "Reg. I", "Pangasinan",
    "..REGION II (CAGAYAN VALLEY)", "Cagayan Valley", "Reg. II", "Reg. II",
    "....Batanes", "Cagayan Valley", "Reg. II", "Batanes",
    "....Cagayan", "Cagayan Valley", "Reg. II", "Cagayan",
    "....Isabela", "Cagayan Valley", "Reg. II", "Isabela",
    "....Nueva Vizcaya", "Cagayan Valley", "Reg. II", "Nueva Vizcaya",
    "....Quirino", "Cagayan Valley", "Reg. II", "Quirino",
    "..REGION III (CENTRAL LUZON)", "Central Luzon", "Reg. III", "Reg. III",
    "....Aurora", "Central Luzon", "Reg. III", "Aurora",
    "....Bataan", "Central Luzon", "Reg. III", "Bataan",
    "....Bulacan", "Central Luzon", "Reg. III", "Bulacan",
    "....Nueva Ecija", "Central Luzon", "Reg. III", "Nueva Ecija",
    "....Pampanga", "Central Luzon", "Reg. III", "Pampanga",
    "....Tarlac", "Central Luzon", "Reg. III", "Tarlac",
    "....Zambales", "Central Luzon", "Reg. III", "Zambales",
    "..REGION IV-A (CALABARZON)", "CALABARZON", "Reg. IV-A", "Reg. IV-A",
    "....Batangas", "CALABARZON", "Reg. IV-A", "Batangas",
    "....Cavite", "CALABARZON", "Reg. IV-A", "Cavite",
    "....Laguna", "CALABARZON", "Reg. IV-A", "Laguna",
    "....Quezon", "CALABARZON", "Reg. IV-A", "Quezon",
    "....Rizal", "CALABARZON", "Reg. IV-A", "Rizal",
    "..MIMAROPA REGION", "MIMAROPA", "Reg. IV-B", "Reg. IV-B",
    "....Marinduque", "MIMAROPA", "Reg. IV-B", "Marinduque",
    "....Occidental Mindoro", "MIMAROPA", "Reg. IV-B", "Occidental Mindoro",
    "....Oriental Mindoro", "MIMAROPA", "Reg. IV-B", "Oriental Mindoro",
    "....Palawan", "MIMAROPA", "Reg. IV-B", "Palawan",
    "....Romblon", "MIMAROPA", "Reg. IV-B", "Romblon",
    "..REGION V (BICOL REGION)", "Bicol Region", "Reg. V", "Reg. V",
    "....Albay", "Bicol Region", "Reg. V", "Albay",
    "....Camarines Norte", "Bicol Region", "Reg. V", "Camarines Norte",
    "....Camarines Sur", "Bicol Region", "Reg. V", "Camarines Sur",
    "....Catanduanes", "Bicol Region", "Reg. V", "Catanduanes",
    "....Masbate", "Bicol Region", "Reg. V", "Masbate",
    "....Sorsogon", "Bicol Region", "Reg. V", "Sorsogan",
    "..REGION VI (WESTERN VISAYAS)", "Western Visayas", "Reg. VI", "Reg. VI",
    "....Aklan", "Western Visayas", "Reg. VI", "Aklan",
    "....Antique", "Western Visayas", "Reg. VI", "Antique",
    "....Capiz", "Western Visayas", "Reg. VI", "Capiz",
    "....Guimaras", "Western Visayas", "Reg. VI", "Guimaras",
    "....Iloilo", "Western Visayas", "Reg. VI", "Iloilo",
    "....Negros Occidental", "Western Visayas", "Reg. VI", "Negros Occidental",
    "..REGION VII (CENTRAL VISAYAS)", "Central Visayas", "Reg. VII", "Reg. VII",
    "....Bohol", "Central Visayas", "Reg. VII", "Bohol",
    "....Cebu", "Central Visayas", "Reg. VII", "Cebu",
    "....Negros Oriental", "Central Visayas", "Reg. VII", "Negros Oriental",
    "....Siquijor", "Central Visayas", "Reg. VII", "Siquijor",
    "..REGION VIII (EASTERN VISAYAS)", "Eastern Visayas", "Reg. VIII", "Reg. VIII",
    "....Biliran", "Eastern Visayas", "Reg. VIII", "Biliran",
    "....Eastern Samar", "Eastern Visayas", "Reg. VIII", "Eastern Samar",
    "....Leyte", "Eastern Visayas", "Reg. VIII", "Leyte",
    "....Northern Samar", "Eastern Visayas", "Reg. VIII", "Northern Samar",
    "....Samar", "Eastern Visayas", "Reg. VIII", "Samar",
    "....Southern Leyte", "Eastern Visayas", "Reg. VIII", "Southern Leyte",
    "..REGION IX (ZAMBOANGA PENINSULA)", "Zamboanga Peninsula", "Reg. IX", "Reg. IX",
    "....Zamboanga del Norte", "Zamboanga Peninsula", "Reg. IX", "Zamboanga del Norte",
    "....Zamboanga del Sur", "Zamboanga Peninsula", "Reg. IX", "Zamboanga del Sur",
    "....Zamboanga Sibugay", "Zamboanga Peninsula", "Reg. IX", "Zamboanga Sibugay",
    "....City of Zamboanga", "Zamboanga Peninsula", "Reg. IX", "City of Zamboanga",
    "....Zamboanga City", "Zamboanga Peninsula", "Reg. IX", "City of Zamboanga",
    "....City of Isabela", "Zamboanga Peninsula", "Reg. IX", "City of Isabela",
    "..REGION X (NORTHERN MINDANAO)", "Northern Mindanao", "Reg. X", "Reg. X",
    "....Bukidnon", "Northern Mindanao", "Reg. X", "Bukidnon",
    "....Camiguin", "Northern Mindanao", "Reg. X", "Camiguin",
    "....Lanao del Norte", "Northern Mindanao", "Reg. X", "Lanao del Norte",
    "....Misamis Occidental", "Northern Mindanao", "Reg. X", "Misamis Occidental",
    "....Misamis Oriental", "Northern Mindanao", "Reg. X", "Misamis Oriental",
    "..REGION XI (DAVAO REGION)", "Davao Region", "Reg. XI", "Reg. XI",
    "....Davao de Oro", "Davao Region", "Reg. XI", "Davao de Oro",
    "....Davao de Oro (Compostela Valley)", "Davao Region", "Reg. XI", "Davao de Oro",
    "....Compostela Valley", "Davao Region", "Reg. XI", "Davao de Oro",
    "....Davao del Norte", "Davao Region", "Reg. XI", "Davao del Norte",
    "....Davao del Sur", "Davao Region", "Reg. XI", "Davao del Sur",
    "....Davao Occidental", "Davao Region", "Reg. XI", "Davao Occidental",
    "....Davao Oriental", "Davao Region", "Reg. XI", "Davao Oriental",
    "....City of Davao", "Davao Region", "Reg. XI", "City of Davao",
    "..REGION XII (SOCCSKSARGEN)", "SOCCSKSARGEN", "Reg. XII", "Reg. XII",
    "....Cotabato", "SOCCSKSARGEN", "Reg. XII", "Cotabato",
    "....Cotabato (North Cotabato)", "SOCCSKSARGEN", "Reg. XII", "Cotabato",
    "....Sarangani", "SOCCSKSARGEN", "Reg. XII", "Sarangani",
    "....Sultan Kudarat", "SOCCSKSARGEN", "Reg. XII", "Sultan Kudarat",
    "....South Cotabato", "SOCCSKSARGEN", "Reg. XII", "South Cotabato",
    "....City of Cotabato", "SOCCSKSARGEN", "Reg. XII", "City of Cotabato",
    "..REGION XIII (CARAGA)", "Caraga Region", "Reg. XIII", "Reg. XIII",
    "....Agusan del Norte", "Caraga Region", "Reg. XIII", "Agusan del Norte",
    "....Agusan del Sur", "Caraga Region", "Reg. XIII", "Agusan del Sur",
    "....Dinagat Islands", "Caraga Region", "Reg. XIII", "Dinagat Islands",
    "....Surigao del Norte", "Caraga Region", "Reg. XIII", "Surigao del Norte",
    "....Surigao del Sur", "Caraga Region", "Reg. XIII", "Surigao del Sur",
    "..AUTONOMOUS REGION IN MUSLIM MINDANAO (ARMM)", "BARMM", "BARMM", "BARMM", 
    "..BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO (BARMM)", "BARMM", "BARMM", "BARMM",
    "....Basilan", "BARMM", "BARMM", "Basilan",
    "....Lanao del Sur", "BARMM", "BARMM", "Lanao del Sur",
    "....Maguindanao", "BARMM", "BARMM", "Maguindanao",
    "....Sulu", "BARMM", "BARMM", "Sulu",
    "....Tawi-Tawi", "BARMM", "BARMM", "Tawi-tawi",
    "....Tawi-tawi", "BARMM", "BARMM", "Tawi-tawi",
    "..AREAS OUTSIDE NATIONAL CAPITAL REGION (NCR)", "AONCR", "AONCR", "AONCR") %>%
    mutate(Geolevel = case_when(str_detect(Geolocation, "\\.{3}") ~ "Province",
                                Geolocation == "PHILIPPINES" ~ "Country",
                                TRUE ~ "Region")) %>%
    select(Geolocation, Geolevel, Region, Reg_Num, Province)

regnums <- c("Philippines", "NCR", "CAR",
             paste("Reg.", c("I", "II", "III", "IV-A", "IV-B", "V",
                             "VI", "VII", "VIII",
                             "IX", "X", "XI", "XII", "XIII")),
             "BARMM")

reglabs <- c("Philippines", "NCR", "CAR",
             "Ilocos Region", "Cagayan Valley", "Central Luzon", "CALABARZON",
             "MIMAROPA", "Bicol Region", "Western Visayas", "Central Visayas",
             "Eastern Visayas", "Zamboanga Peninsula", "Northern Mindanao",
             "Davao Region", "SOCCSKSARGEN", "Caraga Region",
             "BARMM")

commodities <- c("Palay, dry (conv. to 14% mc)",
                 "Regular Milled Rice (RMR)", "Well Milled Rice (WMR)",
                 "Rice Premium", "Rice Special")
